namespace NodeJS {
	interface ProcessEnv {
		NEXT_PUBLIC_GOOGLE_VERIFICATION_CODE: string;
		NEXT_PUBLIC_RECAPTCHA_SITE_KEY: string;
		NEXT_PUBLIC_DISABLE_RECAPTCHA: string;
		NEXT_PUBLIC_DOMAIN: string;

		MY_EMAIL_ADDRESS: string;
		RESEND_API_KEY: string;
		RESEND_TEMPLATE_ID: string;
		RECAPTCHA_SECRET_KEY: string;
	}
}
